from __future__ import annotations

import json
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path


class TestGraphRenderTopology(unittest.TestCase):
    def _fixture(self, root: Path) -> tuple[Path, Path]:
        repo = root / "repo"
        (repo / "pkg").mkdir(parents=True)
        (repo / "pkg" / "resolver.py").write_text("def resolve():\n    return 'ok'\n", encoding="utf-8")
        (repo / "pkg" / "other.py").write_text("def other():\n    return 'ok'\n", encoding="utf-8")
        graph = root / "graph.json"
        graph.write_text(
            json.dumps(
                {
                    "kind": "openclaw-mem.graph.code-extract.v0",
                    "topology_digest": "digest-a",
                    "counts": {"nodes": 2, "edges": 1, "node_types": {"file": 2}, "edge_types": {"imports": 1}},
                    "nodes": [
                        {"id": "file.pkg/resolver.py", "type": "file", "metadata": {"source_path": "pkg/resolver.py", "receipt_id": "r1"}},
                        {"id": "file.pkg/other.py", "type": "file", "metadata": {"source_path": "pkg/other.py", "receipt_id": "r2"}},
                    ],
                    "edges": [{"src": "file.pkg/resolver.py", "dst": "file.pkg/other.py", "type": "imports", "provenance": "pkg/resolver.py#L1"}],
                },
                sort_keys=True,
            ),
            encoding="utf-8",
        )
        return repo, graph

    def test_render_topology_is_deterministic_and_generated_only(self) -> None:
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            repo, graph = self._fixture(root)
            out = root / "generated-a"
            cmd = [sys.executable, "-m", "openclaw_mem", "--json", "graph", "render", "topology", "--repo", str(repo), "--graph", str(graph), "--out", str(out)]
            first = subprocess.run(cmd, cwd=Path(__file__).resolve().parents[1], capture_output=True, text=True, encoding="utf-8", errors="replace")
            self.assertEqual(first.returncode, 0, first.stderr)
            snapshot = {p.name: p.read_text(encoding="utf-8") for p in sorted(out.iterdir())}
            out_b = root / "generated-b"
            cmd_b = [sys.executable, "-m", "openclaw_mem", "--json", "graph", "render", "topology", "--repo", str(repo), "--graph", str(graph), "--out", str(out_b)]
            second = subprocess.run(cmd_b, cwd=Path(__file__).resolve().parents[1], capture_output=True, text=True, encoding="utf-8", errors="replace")
            self.assertEqual(second.returncode, 0, second.stderr)
            self.assertEqual(snapshot, {p.name: p.read_text(encoding="utf-8") for p in sorted(out_b.iterdir())})
            self.assertIn("GENERATED by openclaw-mem graph render topology", snapshot["topology-summary.md"])
            self.assertIn("%% nodes: 2 edges: 1", snapshot["topology-graph.md"])
            expected_root = Path(__file__).parent / "data" / "graph_render_topology" / "expected"
            for name in ["drift-report.json", "module-map.json", "topology-graph.md", "topology-summary.md"]:
                self.assertEqual(snapshot[name], (expected_root / name).read_text(encoding="utf-8"))
            module_map = json.loads(snapshot["module-map.json"])
            self.assertEqual(module_map["modules"][0]["source_path"], "pkg/other.py")
            self.assertTrue(all(item["source_exists"] for item in module_map["modules"]))
            self.assertFalse((root / ".private" / "topology" / "graph-memory-implementation-checklist-2026-07-07.md").exists())

    def test_render_topology_drift_reports_added_node(self) -> None:
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            repo, graph = self._fixture(root)
            out = root / "generated"
            cmd = [sys.executable, "-m", "openclaw_mem", "--json", "graph", "render", "topology", "--repo", str(repo), "--graph", str(graph), "--out", str(out)]
            subprocess.run(cmd, cwd=Path(__file__).resolve().parents[1], check=True, capture_output=True, text=True, encoding="utf-8", errors="replace")
            obj = json.loads(graph.read_text(encoding="utf-8"))
            obj["nodes"].append({"id": "file.pkg/new.py", "type": "file", "metadata": {"source_path": "pkg/new.py", "receipt_id": "r3"}})
            graph.write_text(json.dumps(obj, sort_keys=True), encoding="utf-8")
            subprocess.run(cmd, cwd=Path(__file__).resolve().parents[1], check=True, capture_output=True, text=True, encoding="utf-8", errors="replace")
            drift = json.loads((out / "drift-report.json").read_text(encoding="utf-8"))["drift"]
            self.assertEqual(drift["added"], ["file.pkg/new.py"])


if __name__ == "__main__":
    unittest.main()
