from __future__ import annotations

import subprocess
import sys
import unittest
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SCRIPT = REPO_ROOT / "scripts" / "generate_agent_memory_skill_assets.py"
GLOBAL_CARD = REPO_ROOT / "skills" / "memory" / "SKILL.md"
READONLY_CARD = REPO_ROOT / "skills" / "memory" / "variants" / "readonly.md"


class TestAgentMemorySkillAssets(unittest.TestCase):
    def test_generated_agent_memory_skill_assets_are_fresh(self):
        proc = subprocess.run(
            [sys.executable, str(SCRIPT), "--check"],
            cwd=REPO_ROOT,
            capture_output=True,
            text=True, encoding="utf-8", errors="replace",
            check=False,
        )
        self.assertEqual(proc.returncode, 0, proc.stdout + proc.stderr)
        self.assertIn("OK agent-memory skill assets are up to date", proc.stdout)

    def test_canonical_skill_cards_keep_required_sections(self):
        global_text = GLOBAL_CARD.read_text(encoding="utf-8")
        readonly_text = READONLY_CARD.read_text(encoding="utf-8")
        self.assertTrue(global_text.startswith("---\n"))
        self.assertIn("## Decision table", global_text)
        self.assertIn("## Iron rules", global_text)
        self.assertIn("references/trust-hygiene.md", global_text)
        self.assertIn("Inherit `skills/memory/SKILL.md`", readonly_text)

    def test_generated_assets_are_marked_autogenerated(self):
        for rel in [
            "docs/agent-memory-skill-cards.md",
            "docs/snippets/openclaw-agentturn-message.global-default.md",
            "docs/snippets/openclaw-agentturn-message.watchdog-readonly.md",
        ]:
            text = (REPO_ROOT / rel).read_text(encoding="utf-8")
            self.assertTrue(
                text.splitlines()[0].startswith("<!-- AUTO-GENERATED by scripts/generate_agent_memory_skill_assets.py"),
                rel,
            )


if __name__ == "__main__":
    unittest.main()
