from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, Iterable, List, Tuple

GENERATED_HEADER = (
    "<!-- GENERATED by openclaw-mem graph render topology. "
    "Review-only derived artifact; not source of truth. -->"
)
TOPOLOGY_RENDER_KIND = "openclaw-mem.graph.render-topology.v0"


def _stable_json(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))


def _load_graph(path: str | Path) -> Dict[str, Any]:
    obj = json.loads(Path(path).read_text(encoding="utf-8"))
    if not isinstance(obj, dict):
        raise ValueError("graph root must be an object")
    if not isinstance(obj.get("nodes"), list) or not isinstance(obj.get("edges"), list):
        raise ValueError("graph requires nodes and edges lists")
    return obj


def _node_key(node: Dict[str, Any]) -> Tuple[str, str]:
    return (str(node.get("id") or ""), str(node.get("type") or ""))


def _edge_key(edge: Dict[str, Any]) -> Tuple[str, str, str, str]:
    return (
        str(edge.get("src") or ""),
        str(edge.get("dst") or ""),
        str(edge.get("type") or ""),
        str(edge.get("provenance") or ""),
    )


def _metadata(item: Dict[str, Any]) -> Dict[str, Any]:
    meta = item.get("metadata")
    return meta if isinstance(meta, dict) else {}


def _source_path(node: Dict[str, Any]) -> str:
    meta = _metadata(node)
    return str(meta.get("source_path") or meta.get("path") or "").replace("\\", "/")


def _module_map(nodes: Iterable[Dict[str, Any]], repo: Path) -> List[Dict[str, Any]]:
    out: List[Dict[str, Any]] = []
    for node in nodes:
        source_path = _source_path(node)
        if not source_path or source_path == ".":
            continue
        out.append(
            {
                "node_id": str(node.get("id") or ""),
                "node_type": str(node.get("type") or ""),
                "source_path": source_path,
                "source_exists": (repo / source_path).is_file(),
                "span": _metadata(node).get("span"),
                "receipt_id": str(_metadata(node).get("receipt_id") or ""),
            }
        )
    return sorted(out, key=lambda item: (item["source_path"], item["node_id"]))


def _mermaid(nodes: List[Dict[str, Any]], edges: List[Dict[str, Any]]) -> str:
    lines = [
        GENERATED_HEADER,
        "```mermaid",
        "graph TD",
        f"%% nodes: {len(nodes)} edges: {len(edges)}",
    ]
    for node in nodes:
        node_id = str(node.get("id") or "")
        label = node_id.replace('"', "'")
        safe = _safe_mermaid_id(node_id)
        lines.append(f'  {safe}["{label}"]')
    node_ids = {str(node.get("id") or "") for node in nodes}
    for edge in edges:
        src = str(edge.get("src") or "")
        dst = str(edge.get("dst") or "")
        if src not in node_ids or dst not in node_ids:
            continue
        label = str(edge.get("type") or "edge").replace('"', "'")
        lines.append(f'  {_safe_mermaid_id(src)} -->|"{label}"| {_safe_mermaid_id(dst)}')
    lines.extend(["```", ""])
    return "\n".join(lines)


def _safe_mermaid_id(raw: str) -> str:
    out = []
    for ch in raw:
        out.append(ch if ch.isalnum() else "_")
    token = "".join(out).strip("_")
    return "n_" + (token or "node")


def _summary(graph: Dict[str, Any], nodes: List[Dict[str, Any]], edges: List[Dict[str, Any]]) -> str:
    counts = graph.get("counts") if isinstance(graph.get("counts"), dict) else {}
    node_types = counts.get("node_types") if isinstance(counts.get("node_types"), dict) else {}
    edge_types = counts.get("edge_types") if isinstance(counts.get("edge_types"), dict) else {}
    lines = [
        GENERATED_HEADER,
        "",
        "# Generated Graph Topology Summary",
        "",
        f"- Graph kind: `{graph.get('kind') or 'unknown'}`",
        f"- Nodes: `{len(nodes)}`",
        f"- Edges: `{len(edges)}`",
        f"- Topology digest: `{graph.get('topology_digest') or 'unknown'}`",
        "",
        "## Node Types",
        "",
    ]
    for key in sorted(node_types):
        lines.append(f"- `{key}`: `{node_types[key]}`")
    if not node_types:
        lines.append("- `(none)`: `0`")
    lines.extend(["", "## Edge Types", ""])
    for key in sorted(edge_types):
        lines.append(f"- `{key}`: `{edge_types[key]}`")
    if not edge_types:
        lines.append("- `(none)`: `0`")
    lines.append("")
    return "\n".join(lines)


def _existing_module_map(path: Path) -> Dict[str, Dict[str, Any]]:
    if not path.is_file():
        return {}
    try:
        obj = json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}
    items = obj.get("modules") if isinstance(obj, dict) else None
    if not isinstance(items, list):
        return {}
    return {str(item.get("node_id") or ""): item for item in items if isinstance(item, dict)}


def _drift(previous: Dict[str, Dict[str, Any]], current: List[Dict[str, Any]]) -> Dict[str, Any]:
    current_by_id = {str(item.get("node_id") or ""): item for item in current}
    added = sorted(set(current_by_id) - set(previous))
    removed = sorted(set(previous) - set(current_by_id))
    changed = []
    for node_id in sorted(set(current_by_id) & set(previous)):
        if _stable_json(current_by_id[node_id]) != _stable_json(previous[node_id]):
            changed.append(node_id)
    return {
        "status": "first_render" if not previous else ("changed" if added or removed or changed else "unchanged"),
        "added": added,
        "removed": removed,
        "changed": changed,
    }


def render_topology(*, repo: str | Path, graph: str | Path, out: str | Path) -> Dict[str, Any]:
    repo_path = Path(repo).resolve()
    out_path = Path(out).resolve()
    out_path.mkdir(parents=True, exist_ok=True)
    if not out_path.is_dir():
        raise ValueError(f"output path is not a directory: {out_path}")

    graph_obj = _load_graph(graph)
    nodes = sorted([n for n in graph_obj.get("nodes", []) if isinstance(n, dict)], key=lambda n: (_node_key(n), _stable_json(n)))
    edges = sorted([e for e in graph_obj.get("edges", []) if isinstance(e, dict)], key=lambda e: (_edge_key(e), _stable_json(e)))
    module_map = _module_map(nodes, repo_path)
    module_map_path = out_path / "module-map.json"
    previous = _existing_module_map(module_map_path)
    drift = _drift(previous, module_map)

    summary_path = out_path / "topology-summary.md"
    mermaid_path = out_path / "topology-graph.md"
    drift_path = out_path / "drift-report.json"
    summary_path.write_text(_summary(graph_obj, nodes, edges), encoding="utf-8")
    mermaid_path.write_text(_mermaid(nodes, edges), encoding="utf-8")
    module_map_path.write_text(
        json.dumps({"kind": TOPOLOGY_RENDER_KIND, "modules": module_map}, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    drift_path.write_text(json.dumps({"kind": TOPOLOGY_RENDER_KIND, "drift": drift}, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    return {
        "kind": TOPOLOGY_RENDER_KIND,
        "repo": str(repo_path),
        "graph": str(Path(graph).resolve()),
        "out": str(out_path),
        "files": {
            "summary": str(summary_path),
            "mermaid": str(mermaid_path),
            "module_map": str(module_map_path),
            "drift": str(drift_path),
        },
        "counts": {"nodes": len(nodes), "edges": len(edges), "modules": len(module_map)},
        "source_links": {
            "checked": len(module_map),
            "missing": [item["source_path"] for item in module_map if not item.get("source_exists")],
        },
        "drift": drift,
        "writes_performed": 4,
        "policy": {"mode": "derived_review_only", "source_of_truth": False},
    }
